version: '3.8'

services:
  db:
    image: postgres:15
    container_name: minesweeper-db
    restart: always
    environment:
      POSTGRES_DB: minesweeper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: